{{- if .Values.secrets.logstashWriter.create }}
kind: Secret
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: logstash-writer-user
stringData:
{{- if eq .Values.environment "dev" }}
  users: |-
    logstash_writer:change_me
{{- else if eq .Values.environment "prod" }}
  users: |-
    logstash_writer:change_me
{{- else if eq .Values.environment "stage" }}
  users: |-
    logstash_writer:change_me
{{- else }}
{{- fail ".Values.environment must be set to either stage, dev or prod" }}
{{- end }}
  users_roles: |-
    logstash-writer:logstash_writer
{{- end }}