{{- if .Values.secrets.terraform_user.create }}
kind: Secret
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: terraform-user
stringData:
{{- if eq .Values.environment "dev" }}
  users: |-
    terraform_user:change_me
{{- else if eq .Values.environment "prod" }}
  users: |-
    terraform_user:change_me
{{- else if eq .Values.environment "stage" }}
  users: |-
    terraform_user:change_me
{{- else }}
{{- fail ".Values.environment must be set to either dev, stage or prod" }}
{{- end }}
  users_roles: |-
   superuser:terraform_user
{{- end }}