{{- if .Values.secrets.logstashWriter.create }}
kind: Secret
apiVersion: v1
metadata:
  name: logstash-writer-role
  namespace: {{ .Release.Namespace }}
stringData:
  roles.yml: |-
    logstash-writer:
      cluster: [ 'manage_index_templates', 'monitor' ]
      indices:
      - names: [ '*' ]
        privileges: ['auto_configure', 'write', 'delete', 'create' ]
