{{- if .Values.secrets.terraform_user.create }}
kind: Secret
apiVersion: v1
metadata:
  name: terraform-user-role
  namespace: {{ .Release.Namespace }}
stringData:
  roles.yml: |-
    terraform-user:
      cluster: [ 'all' ]
      indices:
      - names: [ '*' ]
        privileges: [ 'manage' ]
{{- end }}